### ISSUE TITLE
Error: nextChild is undefined

### ISSUE THREAD

**Issue by tylersnyder** [morishitter/picostyle#2]
I'm trying to use `picostyle` with `webpack`, and I'm running into the following error:

```
bundle.js:9863 Uncaught ReferenceError: nextChild is not defined
    at Object.keys.map.property (http://localhost:8080/dist/bundle.js:9863:25)
    at Array.map (native)
    at parse (http://localhost:8080/dist/bundle.js:9859:21)
    at Object.class.decls.map.decl (http://localhost:8080/dist/bundle.js:9879:185)
    at Array.map (native)
    at http://localhost:8080/dist/bundle.js:9879:173
    at h (http://localhost:8080/dist/bundle.js:9631:7)
    at view (http://localhost:8080/dist/bundle.js:9587:20)
    at Object.__webpack_exports__.a (http://localhost:8080/dist/bundle.js:9595:23)
    at __webpack_require__ (http://localhost:8080/dist/bundle.js:20:30)


Object.keys.map.property | @ | bundle.js:9863
  | parse | @ | bundle.js:9859
  | Object.class.decls.map.decl | @ | bundle.js:9879
  | (anonymous) | @ | bundle.js:9879
  | h | @ | bundle.js:9631
  | view | @ | bundle.js:9587
  | __webpack_exports__.a | @ | bundle.js:9595
  | __webpack_require__ | @ | bundle.js:20
  | (anonymous) | @ | bundle.js:3677
  | __webpack_require__ | @ | bundle.js:20
  | module.exports.ctor.super_ | @ | bundle.js:63
  | (anonymous) | @ | bundle.js:66
```

The line in question is: `const nextChild = nextChild ? child : child + property`

I'm not sure what this is trying to achieve, as it appears `nextChild` will always be undefined. If I replace this line with `const nextChild = child + property` it seems to work properly.

Any help is much appreciated.

Here is a repository containing my code. https://github.com/tylersnyder/picostyle-test

**Comment by morishitter** [comment]
@tylersnyder Good catch 👍 I clone https://github.com/tylersnyder/picostyle-test and run `npm run build`, but I can build 🤔 What is your node version? I'm using node v8.2.0. Why? 😂 

I can build your example, but

> I'm not sure what this is trying to achieve, as it appears nextChild will always be undefined. If I replace this line with const nextChild = child + property it seems to work properly.

You're correct. Feel free to send me a PR :)

Thanks!

**Comment by jbucaran** [comment]
@morishitter Was this a bug introduced when you switched from `var` to `const`?

**Comment by morishitter** [comment]
@jbucaran I don't think so. `nextChild` is not overridden everywhere 👀

**Comment by tylersnyder** [comment]
@morishitter I was on node v8.1.2. Updated to 8.2.0 and I'm still seeing the issue :confused:

Interestingly, it seems to work correctly if I switch back to your webpack config. Mine is only slightly different, as I'm not using the /example directory, and I can't tell what's throwing things off.

I submitted a PR. Thanks for your excellent work on this project. :ok_hand:

**Comment by jbucaran** [comment]
Fixed in https://github.com/morishitter/picostyle/pull/3.
