### ISSUE TITLE
No longer works with Hyperapp

### ISSUE THREAD

**Issue by mindplay-dk** [morishitter/picostyle#34]
The example pen is dead:

https://codepen.io/morishitter/pen/aEpGYN?editors=0010

I switched it back to `@1.0.0` and it worked, so there must have been a breaking change - it errors, you can see the error message in the console.

**Comment by JorgeBucaran** [comment]
@mindplay-dk Yes, because of [this](https://github.com/hyperapp/hyperapp/releases/tag/1.1.0).

**Comment by mrozilla** [comment]
This leads to an interesting question—should picostyle try to check the signature returned from the consumed `h` function?

In the hyperapp case, the fix seems to be trivial:
```diff
- node.props.class = [props.class, cache[key]].filter(Boolean).join(' ');
+ node.attributes.class = [props.class, cache[key]].filter(Boolean).join(' ');
```

However, this breaks for other libraries (and would break again, every time the consumed signature changes). When talking about <1k library, we probably don't want to bloat the boilerplate with hundreds of bytes of checks against every possible signature out there.

Perhaps these "internals" could be optionally overridden in a config object, such as 
```js
picostyle(h, { ...config })
``` 

This at least solves this for people who know the `h` signature.

**Comment by morishitter** [comment]
I'll update picostyle when picodom supports the vdom same as hyperapp. Thanks.
