### ISSUE TITLE
DTS file

### ISSUE THREAD

**Issue by pspeter3** [morishitter/picostyle#4]
I wrote the type definitions for picodom. I was wondering if one for picostyle would be good?

**Comment by jbucaran** [comment]
I think so, yes. Let's hear what @morishitter thinks.

**Comment by morishitter** [comment]
@pspeter3 Thanks! Feel free to send the PR :)

**Comment by jbucaran** [comment]
# Root

Use the [`root`](/docs/api.md#root) to target the DOM node to render into.

##### HTML
```html
<body>
  <div id="app"></div>
</body>
```

##### APP
```jsx
app({
  view: () => <h1>Hi.</h1>,
  root: document.getElementById("app")
})
```

##### RESULT
```html
<body>
  <div id="app">
    <h1>Hi.</h1>
  </div>
</body>
```


Use root to target the dom element for rendering, our render is non-destructive by default

element into the DOM in the supplied container

Render a virtual node into the DOM in the supplied container given the supplied virtual DOM. If the virtual node was previously rendered into the container, this will perform an update on it and only mutate the DOM as necessary, to reflect the latest Inferno virtual node.

Warning: If the container element is not empty before rendering, the content of the container will be overwritten on the initial render.







Use the [`root`](...) to target the top-level element in your application.

```jsx
app({
  view: () => <h1>Hi.</h1>,
  root: document.getElementById("app")
})
```

If a root isn't supplied, the [view](/docs/view.md) is rendered in a new element and appended to the [document.body](https://developer.mozilla.org/en-US/docs/Web/API/Document/body).

```jsx
app({
  view: () => <h1>Hi.</h1>
})
```



```html
<body>
  <h1>Hi.</h1> <!-- The root. -->
</body>
```

**Comment by piyushchauhan2011** [comment]
I'm also looking forward on this one 👍

**Comment by dancespiele** [comment]
I will create a PR for the types.

**Comment by morishitter** [comment]
ref: https://github.com/morishitter/picostyle/pull/39
