### ISSUE TITLE
How to do vendor prefixes? (e.g. -webkit-overflow-scrolling)

### ISSUE THREAD

**Issue by christiankaindl** [morishitter/picostyle#47]
Let's assume I want to have `-webkit-overflow-scrolling: 'touch'` as part of my component's CSS.

Here's what I tried so far:
```js
const Dummy = style('article')({
  '-webkit-overflow-scrolling': 'touch'
})
```
and

```js
const Dummy = style('article')({
  WebkitOverflowScrolling: 'touch'
})
```

From my observations, both variations did not apply the CSS rule. What am I missing?

*[MDN reference for `-webkit-overflow-scrolling'`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling)*

**Comment by christiankaindl** [comment]
Ok, figured it out: Both of the above work!

Picostyle doesn't insert styles that are unknown to the browser it runs in. In the case above I was not using a Webkit browser and therefore the styles weren't injected.

**Comment by 11111000000** [comment]
sad, but postcss-js is very expensive. Is here any lighter solutions?
