### ISSUE TITLE
Atomic pitfal

### ISSUE THREAD

**Issue by pygy** [morishitter/picostyle#5]
Hello @morishitter congrats for the release!

A generic issue with atomic CSS is the fact that such libs ignore the stateful nature of CSS, where the order of definitions matter. Picostyle has the same problem.

In the following example, `Text2` will have a completely red border unless you comment out the `Text` `border-left` definition.

This problem can lead to intractable bugs where changing the order in which components are defined changes the way they look.

```JS
const Text = ps("h1")({
  'border-left': 'solid 5px black'
})
const Text2 = ps("h1")({
  'border': 'solid 5px red',
  'border-left': 'solid 5px black'
})

const Wrapper = ps("div")({
})

const tree = h(Wrapper, {},
  h(Text, {}, "Hi..."),
  h(Text2, {}, "Ho!")
)
```

[Repro here](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ArMIA0IAZgJYy6oDaoAdgIYC2EamO+IsA9tYt8wG60ATgAIAFsIC8wgA7FOSDvQyiAOtQEjpteLHFTZ8xRi07V6oTLCSZcjmHgBPGGrWdq94QBUIAD3jXpMAAKFRBRAEZQgEog4DVhYQByACMOQSQIQQBaGEJ4RNQksA4oYiRhAFZpH2FkqFpYAGtEtQBfKNcuD28-ACYA4NCI6Nj4pNT0zIKikrLK6uFBZES8MZS0jOzc-MLE4tLyqpq6hua2jupO938AdUFaaWlMgZCQJGI+EbjqdpdL6jcHngSwg1lEQTuDyegjwwmArVW1ASAHpkcJ6Bw+KD4KJQQADHrwPHCUrUUHJaAcADuwgJvngvWJtGo5WI-igHA4jTAY1RwloVmI3AgLOQY3BhNh8NhoQAEsQMIrooiEhL6b0pQjhHKOABCZVqC5qEy6IIKWAAV0Y3AwqSQDlh1AtUCgjudruEwIgECiIFaAF0CKTuWgqCALYIoMxRPB4IFUKiLdRpI0AOYYTj0ZEGDgKehsRxPZisBGgCNR9AxuNgBPIpMp9OZ7O2exOJgEQtMdAl-2tIA)

The generated CSS/HTML looks like this:

```HTML
<style>
.p0 {
    border-left: 5px solid black;
}
.p1 {
    border: 5px solid red;
}
</style>

<h1 class='p0'>Hi...</h1>
<h1 class='p0 p1'>Ho!</h1>
 ```

**Comment by morishitter** [comment]
@pygy Thanks for using and your report! I can understand the bug, I will fix it :)

**Comment by pygy** [comment]
Thanks for looking into it :-)

You must invalidate the cache in some scenarios, but I don't have a ready-made solution at hand. I edited the example above because the styles are injected the first time the components are rendered, not when they are created, hence an erroneous comment)

**Comment by pygy** [comment]
Oh, note that a similar issue may happen with conditional at-rules like `@media` or `@supports` if the conditional block appears before an identical unconditional definition.

**Comment by morishitter** [comment]
In your example, the generated API seems the following code 🤔 

![image](https://user-images.githubusercontent.com/1401513/29109445-02cd3044-7d1e-11e7-80ba-b40fec0f738b.png)

I made an example to check on [CodePen](https://codepen.io/morishitter/pen/f0aa883c9671bffd24fc63aa0357db18/). `border-left` can't override `border` in multiple classes ... ? 🤔

**Comment by morishitter** [comment]
> border-left can't override border in multiple classes ... ? 🤔

I've found the problem.

**Comment by morishitter** [comment]
Fixed in https://github.com/morishitter/picostyle/pull/8.
