### ISSUE TITLE
ES6 export

### ISSUE THREAD

**Issue by Idered** [morishitter/picostyle#9]
https://github.com/morishitter/picostyle/blob/88850b9ae479b480d2fdeceba0a0cedba6fb9c88/src/index.js#L47

`export default` is part of ES6. You rewrote whole project to ES5 so this also should be changed to `module.export`

**Comment by jbucaran** [comment]
@Idered Picostyle is bundled with rollup, just like hyperapp and picodom are, so using ES6 import/export is fine.

**Comment by morishitter** [comment]
Yes, I rewrote that according to the hyperapp and picodom.
